# Generated by Django 4.1.1 on 2022-09-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClsDetallesFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.CharField(max_length=500)),
                ('precioUnitario', models.FloatField()),
                ('importe', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'Detalles',
            },
        ),
        migrations.CreateModel(
            name='ClsPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Passwords',
            },
        ),
        migrations.CreateModel(
            name='ClsPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('feliz', models.BooleanField(blank=True)),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('altura', models.FloatField()),
            ],
            options={
                'db_table': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='ClsFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=50)),
                ('direcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('nroPedido', models.IntegerField(verbose_name='pedido')),
                ('nroFactura', models.IntegerField(verbose_name='codigo')),
                ('fechaVencimiento', models.DateField(verbose_name='vencimiento')),
                ('detalles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.clsdetallesfacturas', verbose_name='detalle')),
            ],
            options={
                'db_table': 'Facturas',
            },
        ),
    ]
