# Generated by Django 4.1 on 2022-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClsPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('feliz', models.BooleanField(blank=True)),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('altura', models.FloatField()),
            ],
            options={
                'db_table': 'Personas',
            },
        ),
    ]
